### ISSUE TITLE
PHP Generator Scoped

### ISSUE THREAD

**Issue by Ferror** [asyncapi/modelina#1195]
## Milestones
- [x] Base PHP Generator from the official template (https://github.com/asyncapi/modelina/pull/1196)
- [x] Define PHP reserved words/keywords (https://github.com/asyncapi/modelina/pull/1211)
- [x] Ability to generate classes
- [x] Ability to generate Enums
- [x] Mixed & Nullable Types (https://github.com/asyncapi/modelina/pull/1216)
- [x] Documentation
- [x] Examples (https://github.com/asyncapi/modelina/pull/1218)
- [x] PHP Namespace as a parameter (https://github.com/asyncapi/modelina/pull/1258)
- [x] Render strict types (https://github.com/asyncapi/modelina/pull/1253)
- [ ] Final classes by default and parameter

### Additionals
* How about Backed Enums? https://www.php.net/manual/en/language.enumerations.backed.php

## Thoughts, Ideas, PHP Specifics 

> Let's support only PHP 8.0 and up. PHP 7.4 is already not supported: https://www.php.net/supported-versions.php

### PHP 8.0
* private properties when readonly -> getters
* public properties instead of getters + setters

### PHP 8.1
* public readonly properties
* public properties instead of getters + setters

### PHP 8.2
* public readonly class
* public properties

## Options
* PHP Version (8.0, 8.1, 8.2) default (8.2)
* Readonly properties (true/false) default (true)
* Namespace
